# Generated by Django 4.1.3 on 2022-12-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffsys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admininfo',
            name='username',
            field=models.CharField(max_length=16, verbose_name='管理员名'),
        ),
    ]
