# Generated by Django 4.1.3 on 2022-11-28 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffsys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号码')),
                ('price', models.IntegerField(verbose_name='手机号价格')),
                ('level', models.SmallIntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], default=1, verbose_name='手机号级别')),
                ('status', models.SmallIntegerField(choices=[(1, '已占用'), (2, '未使用')], default=2, verbose_name='状态')),
                ('create_time', models.DateTimeField(verbose_name='首次上传时间')),
            ],
        ),
        migrations.AlterField(
            model_name='staff_info',
            name='depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffsys.staff_department', verbose_name='部门'),
        ),
    ]
