# Generated by Django 4.1.3 on 2022-12-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffsys', '0002_alter_admininfo_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admininfo',
            name='password',
            field=models.CharField(max_length=200, verbose_name='管理员密码'),
        ),
    ]
