# Generated by Django 4.1.3 on 2022-11-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffsys', '0004_alter_mobile_info_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile_info',
            name='update_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='修改时间'),
        ),
    ]
