# Generated by Django 4.1.3 on 2022-11-28 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffsys', '0005_alter_mobile_info_update_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobile_info',
            name='update_time',
        ),
    ]
